name: Keep Alive Ping
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  keep_alive:
    runs-on: ubuntu-latest
    env:
      ENDPOINTS: |
        https://server-backend-j3bt.onrender.com/auth/google
        https://job-aware-api.onrender.com/
    steps:
      - name: Ping all endpoints with retry & delay
        id: ping
        run: |
          FAILURES=""
          RETRIES=5
          DELAY=10
          while read -r url; do
            [[ -z "$url" ]] && continue  # <-- This line skips blanks
            echo "🔄 Pinging $url (up to $RETRIES attempts)"
            for i in $(seq 1 $RETRIES); do
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$url")
              echo "Attempt $i: $url => $STATUS"
              if [[ "$STATUS" -eq 200 || "$STATUS" -eq 302 ]]; then
                echo "✅ Success on attempt $i"
                break
              fi
              if [[ "$i" -lt $RETRIES ]]; then
                echo "⏳ Waiting $DELAY seconds before retrying..."
                sleep $DELAY
              else
                echo "❌ $url failed after $RETRIES retries"
                FAILURES+="$url failed after $RETRIES retries with last status $STATUS\n"
              fi
            done
          done <<< "${ENDPOINTS}"
      
          if [ -n "$FAILURES" ]; then
            echo "failures=true" >> "$GITHUB_OUTPUT"
            echo "failure_log=$FAILURES" >> "$GITHUB_OUTPUT"
          else
            echo "failures=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Send email on failure
        if: steps.ping.outputs.failures == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_PASS }}
          subject: "⚠️ Keep-Alive Ping Failure Detected"
          body: |
            One or more backend endpoints failed to respond successfully after retries.
            ${{ steps.ping.outputs.failure_log }}
            Timestamp: ${{ github.event.schedule }}
          to: "bhushanmahajan2908@gmail.com"
          from: "Keep-Alive Bot <bhushanmahajan2908@gmail.com>"
